#!/usr/bin/env bash
# Build the selected backend (BACKEND_LANGUAGE = node | python | dotnet)
# into ./src/api/ so azd can package it as a single `api` service.
set -euo pipefail

LANG_VAL="${BACKEND_LANGUAGE:-node}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/src/api"

echo "build-api: language = $LANG_VAL"
mkdir -p "$OUT"
# Clean *contents* (not the dir itself) so file watchers don't error.
find "$OUT" -mindepth 1 -maxdepth 1 -exec rm -rf {} +

case "$LANG_VAL" in
  node)
    SRC="$ROOT/src/api-node"
    cp -r "$SRC"/. "$OUT"/
    rm -f "$OUT/local.settings.json"
    ( cd "$OUT" && npm install --omit=dev --no-audit --no-fund --silent )
    ;;
  python)
    SRC="$ROOT/src/api-python"
    cp -r "$SRC"/. "$OUT"/
    rm -f "$OUT/local.settings.json"
    # Function App runs Python 3.11 on linux/x86_64. Force matching wheels.
    python -m pip install --quiet \
      --target "$OUT/.python_packages/lib/site-packages" \
      --platform manylinux2014_x86_64 \
      --python-version 3.11 \
      --implementation cp \
      --only-binary=:all: \
      --upgrade \
      -r "$OUT/requirements.txt"
    ;;
  dotnet)
    SRC="$ROOT/src/api-dotnet/Api.Dotnet.csproj"
    # Flex Consumption requires a pre-published package that contains the
    # .azurefunctions/ directory at the root — produced by `dotnet publish`.
    dotnet publish "$SRC" -c Release -o "$OUT" --nologo -v quiet
    rm -f "$OUT/local.settings.json"
    ;;
  *)
    echo "ERROR: BACKEND_LANGUAGE must be one of: node, python, dotnet (got '$LANG_VAL')" >&2
    exit 1
    ;;
esac

# azd's `host: function` + `language: js` flow runs `npm install` and
# `npm run build` against src/api. Ensure a package.json with a no-op
# build script always exists — the node branch writes a real one,
# others write this stub.
if [ ! -f "$OUT/package.json" ]; then
  cat > "$OUT/package.json" <<EOF
{
  "name": "api",
  "version": "1.0.0",
  "private": true,
  "description": "Generated by scripts/build-api.sh ($LANG_VAL). Do not edit.",
  "scripts": { "build": "echo done" }
}
EOF
fi

echo "build-api: wrote $OUT"
