#!/usr/bin/env pwsh
# Build the selected backend (BACKEND_LANGUAGE = node | python | dotnet)
# into ./src/api/ so azd can package it as a single `api` service.
[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'

$lang = if ($env:BACKEND_LANGUAGE) { $env:BACKEND_LANGUAGE } else { 'node' }
$root = Resolve-Path (Join-Path $PSScriptRoot '..')
$out  = Join-Path $root 'src/api'

Write-Host "build-api: language = $lang"
if (-not (Test-Path $out)) { New-Item -ItemType Directory -Path $out | Out-Null }
Get-ChildItem -Force -Path $out | ForEach-Object {
  Remove-Item $_.FullName -Recurse -Force -ErrorAction SilentlyContinue
}

switch ($lang) {
  'node' {
    $src = Join-Path $root 'src/api-node'
    Copy-Item -Recurse -Force "$src/*" $out
    Remove-Item -Force (Join-Path $out 'local.settings.json') -ErrorAction SilentlyContinue
    Push-Location $out
    try { npm install --omit=dev --no-audit --no-fund --silent }
    finally { Pop-Location }
  }
  'python' {
    $src = Join-Path $root 'src/api-python'
    Copy-Item -Recurse -Force "$src/*" $out
    Remove-Item -Force (Join-Path $out 'local.settings.json') -ErrorAction SilentlyContinue
    $pkgs = Join-Path $out '.python_packages/lib/site-packages'
    # Function App runs Python 3.11 on linux/x86_64. Force matching wheels
    # so this works from any host (Windows ARM64, macOS, etc.).
    python -m pip install --quiet --target $pkgs `
      --platform manylinux2014_x86_64 `
      --python-version 3.11 `
      --implementation cp `
      --only-binary=:all: `
      --upgrade `
      -r (Join-Path $out 'requirements.txt')
    if ($LASTEXITCODE -ne 0) { throw "pip install failed" }
  }
  'dotnet' {
    $src = Join-Path $root 'src/api-dotnet/Api.Dotnet.csproj'
    # Flex Consumption requires a pre-published package that contains the
    # .azurefunctions/ directory at the root — produced by `dotnet publish`.
    dotnet publish $src -c Release -o $out --nologo -v quiet
    if ($LASTEXITCODE -ne 0) { throw "dotnet publish failed" }
    Remove-Item -Force (Join-Path $out 'local.settings.json') -ErrorAction SilentlyContinue
  }
  default {
    throw "BACKEND_LANGUAGE must be one of: node, python, dotnet (got '$lang')"
  }
}

# azd's `host: function` + `language: js` flow runs `npm install` and
# `npm run build` against src/api. Ensure a package.json with no-op
# scripts always exists — the node branch writes a real one, others write
# this stub.
$pkg = Join-Path $out 'package.json'
if (-not (Test-Path $pkg)) {
  $stub = @{
    name        = 'api'
    version     = '1.0.0'
    private     = $true
    description = "Generated by scripts/build-api.ps1 ($lang). Do not edit."
    scripts     = @{ build = 'echo done' }
  } | ConvertTo-Json -Depth 4
  Set-Content -Path $pkg -Value $stub -Encoding utf8
}

Write-Host "build-api: wrote $out"
